[package]
name = "daemon-plugin"
version = "0.1.2"
edition = "2021"
publish = false

[lib]
name = "daemon_plugin"
path = "src/lib.rs"

[[bin]]
name = "daemon"
path = "src/main.rs"

[dependencies]
vynkor-sdk = "0.0.3"
vynkor-plugin-manifest = { path = "../_shared/plugin-manifest" }
vynkor-wire = "0.0.2"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "time", "sync"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
